import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import {ClerkProvider} from "@clerk/nextjs";
import { Toaster } from "sonner";
import "./globals.css";
import { ExitModal } from "@/components/modals/exit-modal";
import { HeartsModal } from "@/components/modals/hearts-modal";

const font = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Lingo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <Toaster/>
      <ExitModal/>
      <HeartsModal/>
      <body className={font.className}>{children}</body>
    </html>
    </ClerkProvider>
  );
}
